language: cpp
compiler:
  - clang
  - gcc

branches:
  only:
    - master
    - coverity_scan

before_install:
  - if [[ ${TRAVIS_BRANCH} == 'coverity_scan' && ${CC} != 'gcc' ]]; then exit; fi;
  - sudo apt-get update -qq
install: sudo apt-get install -qq build-essential libsdl1.2debian libsdl-image1.2 libopenal1 libsdl1.2-dev libsdl-image1.2-dev libopenal-dev libvorbis-dev libenet-dev
script:
  - if [ ${COVERITY_SCAN_BRANCH} == 1 ]; then exit; fi
  - cd ./source/src
  - make all

notifications:
  irc:
    channels:
      - "chat.freenode.net#acreloaded-dev"
    template: "%{repository}#%{branch} <%{author}> %{commit} [%{duration}] %{message} (#%{build_number}) %{build_url}"
    on_success: always # [always|never|change] default: always
    on_failure: always # [always|never|change] default: always
    use_notice: false # notices don't show up in OmnomIRC
    skip_join: true

env:
  global:
   # encrypted COVERITY_SCAN_TOKEN
   - secure: "TSLZh9etpZPF/rApCEy5FNOLnwG9/8gY5c+TaUlM24lgZnFX3Hqus0IbXLTnFwYDrEtlGPBnrpQxaWb6SbfKrc6VAQjvtOptVoZ5xQfyyg9CRIZSRr3XW57Yg8RI1LX4hTptd2t2vVrl/xUvHNS21S1E+15gkUISoKqdrDeMvGk="

addons:
  coverity_scan:
    project:
      name: "acreloaded/acr"
      description: "Build submitted via Travis CI"
    notification_email: nobody@domain.invalid
    build_command_prepend: "cd ./source/src"
    build_command:   "make all"
    branch_pattern: coverity_scan
