language:
  - cpp

compiler:
  - gcc
  - clang

env:
  - build=client
  - build=server

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential libsdl1.2debian libsdl-image1.2 libopenal1
  - sudo apt-get install -qq libsdl1.2-dev libsdl-image1.2-dev libopenal-dev libvorbis-dev

script:
  - cd ./source/src
  - chmod +x ../enet/Makefile
  - chmod +x ../enet/configure
  - make $build
